### ISSUE TITLE
How to make this work nicely with stdout from other processes?

### ISSUE THREAD

**Issue by ccorcos** [bvaughn/progress-estimator#13]
I have this unfortunate behavior where the progress bar gets carried along with the other logs. Any ideas how I can fix this?

```
⠹ Building Client  0%                  0.0m, estimated 3.6m
ℹ ｢atl｣: Using typescript@3.0.3 from typescript
⠼ Building Client  20%                 0.7m, estimated 3.6m
(node:42049) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
    at Object.pitch (/Users/chet/Code/notion-next/node_modules/worker-loader/dist/index.js:87:19)
    at LOADER_EXECUTION (/Users/chet/Code/notion-next/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/chet/Code/notion-next/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at /Users/chet/Code/notion-next/node_modules/loader-runner/lib/LoaderRunner.js:175:3
    at loadLoader (/Users/chet/Code/notion-next/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/chet/Code/notion-next/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/chet/Code/notion-next/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/chet/Code/notion-next/node_modules/webpack/lib/NormalModule.js:282:3)
    at NormalModule.build (/Users/chet/Code/notion-next/node_modules/webpack/lib/NormalModule.js:429:15)
    at Compilation.buildModule (/Users/chet/Code/notion-next/node_modules/webpack/lib/Compilation.js:369:10)
    at factory.create (/Users/chet/Code/notion-next/node_modules/webpack/lib/Compilation.js:596:14)
    at factory (/Users/chet/Code/notion-next/node_modules/webpack/lib/NormalModuleFactory.js:405:6)
    at hooks.afterResolve.callAsync (/Users/chet/Code/notion-next/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/Users/chet/Code/notion-next/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at resolver (/Users/chet/Code/notion-next/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
    at process.nextTick (/Users/chet/Code/notion-next/node_modules/webpack/lib/NormalModuleFactory.js:342:9)
⠼ Building Client  67%                 2.4m, estimated 3.6m
```

**Comment by bvaughn** [comment]
You'd have to provide your own `logFunction` as described in the [API docs](https://github.com/bvaughn/progress-estimator/blob/master/README.md#api). By default this library uses log-update and assumes it's the only thing using stdout.

**Comment by ccorcos** [comment]
Hmm. I see that now. Tricky... because I want it always to stay at the bottom...

**Comment by bvaughn** [comment]
You would need to do something like listr does, and wrap log-update so that you can re-route other stdout stuff to it too, just above the progress-estimator output. Does sound a little tricky, yes.
